server:
    port: 8887
    
hystrix:
    command:
        fallbackcmd:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 2000
spring:
  cloud:
    gateway:
      routes:
      - id: adminservice
        uri: lb://adminservice
        predicates:
        - Path=/api/admin/**
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@userKeyResolver}'
            redis-rate-limiter.replenishRate: 2
            redis-rate-limiter.burstCapacity: 2
        - RewritePath=/api/(?<admin>.*), /$\{admin}
        - name: Hystrix
          args:
            name: booksFallbackCommand
            fallbackUri: forward:/fallback/admin
        - AddResponseHeader=X-Some-Header, com.deloitte.msplatform
    discovery:
      client:
        simple:
          instances:
            apigateway:
              - uri: http://localhost:8887
                metadata:
                  management.context-path: /management
            adminservice:
              - uri: http://localhost:8890
                metadata:
                  management.context-path: /management  
            employeeservice:
              - uri: http://localhost:8891
                metadata:
                  management.context-path: /management
    
        
